services:
  strapi:
    container_name: strapi
    image: ghcr.io/blodroed/strapi-blodroed:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: sqlite
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET:?}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET:?}
      APP_KEYS: ${APP_KEYS:?}
      API_TOKEN_SALT: ${API_TOKEN_SALT:?}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT:?}
      PUBLIC_URL: ${PUBLIC_URL}
    volumes:
      - ./public/uploads:/opt/app/public/uploads
      - ./data:/opt/app/.tmp # Persist SQLite database file
    ports:
      - "1337:1337"
    networks:
      - strapi
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:1337/" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 40s
    labels:
      - traefik.http.middlewares.force-https.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.https-0-rwgkw0gkc0swws80wg088oc4-strapi.middlewares=gzip,force-https
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  strapi:
    name: strapi
    driver: bridge